create table "public"."profiles_stats" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile_id" bigint not null,
    "points" bigint not null default '0'::bigint,
    "win" bigint not null default '0'::bigint,
    "loss" bigint not null default '0'::bigint,
    "draw" bigint not null default '0'::bigint,
    "minutes_played" bigint not null default '0'::bigint
);


alter table "public"."matches" alter column "endAt" set data type timestamp with time zone using "endAt"::timestamp with time zone;

alter table "public"."matches" alter column "startAt" set data type timestamp with time zone using "startAt"::timestamp with time zone;

alter table "public"."places_games" disable row level security;

CREATE UNIQUE INDEX profiles_stats_pkey ON public.profiles_stats USING btree (id);

CREATE UNIQUE INDEX profiles_stats_profile_id_key ON public.profiles_stats USING btree (profile_id);

alter table "public"."profiles_stats" add constraint "profiles_stats_pkey" PRIMARY KEY using index "profiles_stats_pkey";

alter table "public"."profiles_stats" add constraint "profiles_stats_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE RESTRICT ON DELETE CASCADE not valid;

alter table "public"."profiles_stats" validate constraint "profiles_stats_profile_id_fkey";

alter table "public"."profiles_stats" add constraint "profiles_stats_profile_id_key" UNIQUE using index "profiles_stats_profile_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_places_by_distance(user_lat double precision, user_lon double precision)
 RETURNS TABLE(id bigint, name text, address text, distance double precision)
 LANGUAGE sql
AS $function$
  select
    id,
    name,
    address,
    ST_DistanceSphere(geom::geometry, ST_MakePoint(user_lon, user_lat)) as distance
  from places
  where geom is not null
  order by distance;
$function$
;

grant delete on table "public"."profiles_stats" to "anon";

grant insert on table "public"."profiles_stats" to "anon";

grant references on table "public"."profiles_stats" to "anon";

grant select on table "public"."profiles_stats" to "anon";

grant trigger on table "public"."profiles_stats" to "anon";

grant truncate on table "public"."profiles_stats" to "anon";

grant update on table "public"."profiles_stats" to "anon";

grant delete on table "public"."profiles_stats" to "authenticated";

grant insert on table "public"."profiles_stats" to "authenticated";

grant references on table "public"."profiles_stats" to "authenticated";

grant select on table "public"."profiles_stats" to "authenticated";

grant trigger on table "public"."profiles_stats" to "authenticated";

grant truncate on table "public"."profiles_stats" to "authenticated";

grant update on table "public"."profiles_stats" to "authenticated";

grant delete on table "public"."profiles_stats" to "service_role";

grant insert on table "public"."profiles_stats" to "service_role";

grant references on table "public"."profiles_stats" to "service_role";

grant select on table "public"."profiles_stats" to "service_role";

grant trigger on table "public"."profiles_stats" to "service_role";

grant truncate on table "public"."profiles_stats" to "service_role";

grant update on table "public"."profiles_stats" to "service_role";


