create table "public"."profiles_locations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile_id" bigint not null,
    "points" bigint not null default '0'::bigint,
    "location_id" bigint not null,
    "win" bigint not null default '0'::bigint,
    "loss" bigint not null default '0'::bigint,
    "draw" bigint not null default '0'::bigint,
    "minutes_played" bigint not null default '0'::bigint
);


CREATE UNIQUE INDEX profiles_locations_pkey ON public.profiles_locations USING btree (id);

alter table "public"."profiles_locations" add constraint "profiles_locations_pkey" PRIMARY KEY using index "profiles_locations_pkey";

alter table "public"."profiles_locations" add constraint "profiles_locations_game_id_fkey" FOREIGN KEY (location_id) REFERENCES games(id) ON DELETE CASCADE not valid;

alter table "public"."profiles_locations" validate constraint "profiles_locations_game_id_fkey";

alter table "public"."profiles_locations" add constraint "profiles_locations_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE RESTRICT ON DELETE RESTRICT not valid;

alter table "public"."profiles_locations" validate constraint "profiles_locations_profile_id_fkey";

grant delete on table "public"."profiles_locations" to "anon";

grant insert on table "public"."profiles_locations" to "anon";

grant references on table "public"."profiles_locations" to "anon";

grant select on table "public"."profiles_locations" to "anon";

grant trigger on table "public"."profiles_locations" to "anon";

grant truncate on table "public"."profiles_locations" to "anon";

grant update on table "public"."profiles_locations" to "anon";

grant delete on table "public"."profiles_locations" to "authenticated";

grant insert on table "public"."profiles_locations" to "authenticated";

grant references on table "public"."profiles_locations" to "authenticated";

grant select on table "public"."profiles_locations" to "authenticated";

grant trigger on table "public"."profiles_locations" to "authenticated";

grant truncate on table "public"."profiles_locations" to "authenticated";

grant update on table "public"."profiles_locations" to "authenticated";

grant delete on table "public"."profiles_locations" to "service_role";

grant insert on table "public"."profiles_locations" to "service_role";

grant references on table "public"."profiles_locations" to "service_role";

grant select on table "public"."profiles_locations" to "service_role";

grant trigger on table "public"."profiles_locations" to "service_role";

grant truncate on table "public"."profiles_locations" to "service_role";

grant update on table "public"."profiles_locations" to "service_role";


