create table "public"."profiles_places" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile_id" bigint not null,
    "points" bigint not null default '0'::bigint,
    "place_id" bigint not null,
    "win" bigint not null default '0'::bigint,
    "loss" bigint not null default '0'::bigint,
    "draw" bigint not null default '0'::bigint,
    "minutes_played" bigint not null default '0'::bigint
);


CREATE UNIQUE INDEX profiles_places_pkey ON public.profiles_places USING btree (id);

alter table "public"."profiles_places" add constraint "profiles_places_pkey" PRIMARY KEY using index "profiles_places_pkey";

alter table "public"."profiles_places" add constraint "profiles_places_game_id_fkey" FOREIGN KEY (place_id) REFERENCES games(id) ON DELETE CASCADE not valid;

alter table "public"."profiles_places" validate constraint "profiles_places_game_id_fkey";

alter table "public"."profiles_places" add constraint "profiles_places_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE RESTRICT ON DELETE RESTRICT not valid;

alter table "public"."profiles_places" validate constraint "profiles_places_profile_id_fkey";

grant delete on table "public"."profiles_places" to "anon";

grant insert on table "public"."profiles_places" to "anon";

grant references on table "public"."profiles_places" to "anon";

grant select on table "public"."profiles_places" to "anon";

grant trigger on table "public"."profiles_places" to "anon";

grant truncate on table "public"."profiles_places" to "anon";

grant update on table "public"."profiles_places" to "anon";

grant delete on table "public"."profiles_places" to "authenticated";

grant insert on table "public"."profiles_places" to "authenticated";

grant references on table "public"."profiles_places" to "authenticated";

grant select on table "public"."profiles_places" to "authenticated";

grant trigger on table "public"."profiles_places" to "authenticated";

grant truncate on table "public"."profiles_places" to "authenticated";

grant update on table "public"."profiles_places" to "authenticated";

grant delete on table "public"."profiles_places" to "service_role";

grant insert on table "public"."profiles_places" to "service_role";

grant references on table "public"."profiles_places" to "service_role";

grant select on table "public"."profiles_places" to "service_role";

grant trigger on table "public"."profiles_places" to "service_role";

grant truncate on table "public"."profiles_places" to "service_role";

grant update on table "public"."profiles_places" to "service_role";


