create table "public"."places_games" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "place_id" bigint,
    "game_id" bigint,
    "copies" integer,
    "rented" integer
);


alter table "public"."places_games" enable row level security;

CREATE UNIQUE INDEX places_games_pkey ON public.places_games USING btree (id);

alter table "public"."places_games" add constraint "places_games_pkey" PRIMARY KEY using index "places_games_pkey";

alter table "public"."places_games" add constraint "places_games_game_id_fkey" FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE not valid;

alter table "public"."places_games" validate constraint "places_games_game_id_fkey";

alter table "public"."places_games" add constraint "places_games_place_id_fkey" FOREIGN KEY (place_id) REFERENCES places(id) not valid;

alter table "public"."places_games" validate constraint "places_games_place_id_fkey";

grant delete on table "public"."places_games" to "anon";

grant insert on table "public"."places_games" to "anon";

grant references on table "public"."places_games" to "anon";

grant select on table "public"."places_games" to "anon";

grant trigger on table "public"."places_games" to "anon";

grant truncate on table "public"."places_games" to "anon";

grant update on table "public"."places_games" to "anon";

grant delete on table "public"."places_games" to "authenticated";

grant insert on table "public"."places_games" to "authenticated";

grant references on table "public"."places_games" to "authenticated";

grant select on table "public"."places_games" to "authenticated";

grant trigger on table "public"."places_games" to "authenticated";

grant truncate on table "public"."places_games" to "authenticated";

grant update on table "public"."places_games" to "authenticated";

grant delete on table "public"."places_games" to "service_role";

grant insert on table "public"."places_games" to "service_role";

grant references on table "public"."places_games" to "service_role";

grant select on table "public"."places_games" to "service_role";

grant trigger on table "public"."places_games" to "service_role";

grant truncate on table "public"."places_games" to "service_role";

grant update on table "public"."places_games" to "service_role";


