alter table "public"."profiles_places" drop constraint "profiles_places_game_id_fkey";

alter table "public"."profiles_games" drop constraint "profiles_games_profile_id_fkey";

alter table "public"."profiles_places" drop constraint "profiles_places_profile_id_fkey";

alter table "public"."profiles_matches" drop constraint "profiles_matches_profile_id_fkey";

create table "public"."user_actions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "action" text
);


create table "public"."users_permissions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default gen_random_uuid(),
    "user_action_id" bigint,
    "place_id" bigint
);


alter table "public"."profiles_games" add column "favourite" boolean not null default false;

alter table "public"."profiles_games" add column "in_collection" boolean not null default false;

alter table "public"."profiles_games" add column "in_wishlist" boolean not null default false;

alter table "public"."profiles_games" add column "rating" double precision;

alter table "public"."profiles_places" add column "favourite" boolean not null default false;

alter table "public"."profiles_matches" add column "confirmed" boolean not null default false;

CREATE UNIQUE INDEX profiles_games_profile_id_game_id_key ON public.profiles_games USING btree (profile_id, game_id);

CREATE UNIQUE INDEX profiles_places_profile_id_place_id_key ON public.profiles_places USING btree (profile_id, place_id);

CREATE UNIQUE INDEX user_actions_pkey ON public.user_actions USING btree (id);

CREATE UNIQUE INDEX users_roles_permissions_pkey ON public.users_permissions USING btree (id);

alter table "public"."user_actions" add constraint "user_actions_pkey" PRIMARY KEY using index "user_actions_pkey";

alter table "public"."users_permissions" add constraint "users_roles_permissions_pkey" PRIMARY KEY using index "users_roles_permissions_pkey";

alter table "public"."profiles_places" add constraint "profiles_places_place_id_fkey" FOREIGN KEY (place_id) REFERENCES places(id) not valid;

alter table "public"."profiles_places" validate constraint "profiles_places_place_id_fkey";

alter table "public"."users_permissions" add constraint "users_roles_permissions_place_id_fkey" FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE CASCADE not valid;

alter table "public"."users_permissions" validate constraint "users_roles_permissions_place_id_fkey";

alter table "public"."users_permissions" add constraint "users_roles_permissions_user_action_id_fkey" FOREIGN KEY (user_action_id) REFERENCES user_actions(id) not valid;

alter table "public"."users_permissions" validate constraint "users_roles_permissions_user_action_id_fkey";

alter table "public"."users_permissions" add constraint "users_roles_permissions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users_permissions" validate constraint "users_roles_permissions_user_id_fkey";

alter table "public"."profiles_games" add constraint "profiles_games_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE RESTRICT ON DELETE CASCADE not valid;

alter table "public"."profiles_games" validate constraint "profiles_games_profile_id_fkey";

alter table "public"."profiles_places" add constraint "profiles_places_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE RESTRICT ON DELETE CASCADE not valid;

alter table "public"."profiles_places" validate constraint "profiles_places_profile_id_fkey";

alter table "public"."profiles_matches" add constraint "profiles_matches_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE RESTRICT ON DELETE CASCADE not valid;

alter table "public"."profiles_matches" validate constraint "profiles_matches_profile_id_fkey";

grant delete on table "public"."user_actions" to "anon";

grant insert on table "public"."user_actions" to "anon";

grant references on table "public"."user_actions" to "anon";

grant select on table "public"."user_actions" to "anon";

grant trigger on table "public"."user_actions" to "anon";

grant truncate on table "public"."user_actions" to "anon";

grant update on table "public"."user_actions" to "anon";

grant delete on table "public"."user_actions" to "authenticated";

grant insert on table "public"."user_actions" to "authenticated";

grant references on table "public"."user_actions" to "authenticated";

grant select on table "public"."user_actions" to "authenticated";

grant trigger on table "public"."user_actions" to "authenticated";

grant truncate on table "public"."user_actions" to "authenticated";

grant update on table "public"."user_actions" to "authenticated";

grant delete on table "public"."user_actions" to "service_role";

grant insert on table "public"."user_actions" to "service_role";

grant references on table "public"."user_actions" to "service_role";

grant select on table "public"."user_actions" to "service_role";

grant trigger on table "public"."user_actions" to "service_role";

grant truncate on table "public"."user_actions" to "service_role";

grant update on table "public"."user_actions" to "service_role";

grant delete on table "public"."users_permissions" to "anon";

grant insert on table "public"."users_permissions" to "anon";

grant references on table "public"."users_permissions" to "anon";

grant select on table "public"."users_permissions" to "anon";

grant trigger on table "public"."users_permissions" to "anon";

grant truncate on table "public"."users_permissions" to "anon";

grant update on table "public"."users_permissions" to "anon";

grant delete on table "public"."users_permissions" to "authenticated";

grant insert on table "public"."users_permissions" to "authenticated";

grant references on table "public"."users_permissions" to "authenticated";

grant select on table "public"."users_permissions" to "authenticated";

grant trigger on table "public"."users_permissions" to "authenticated";

grant truncate on table "public"."users_permissions" to "authenticated";

grant update on table "public"."users_permissions" to "authenticated";

grant delete on table "public"."users_permissions" to "service_role";

grant insert on table "public"."users_permissions" to "service_role";

grant references on table "public"."users_permissions" to "service_role";

grant select on table "public"."users_permissions" to "service_role";

grant trigger on table "public"."users_permissions" to "service_role";

grant truncate on table "public"."users_permissions" to "service_role";

grant update on table "public"."users_permissions" to "service_role";


